package org.ecommerceplatform.dataobject;

public class WalletDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wallet.id
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wallet.balance
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    private Double balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_wallet.user_id
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wallet.id
     *
     * @return the value of user_wallet.id
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wallet.id
     *
     * @param id the value for user_wallet.id
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wallet.balance
     *
     * @return the value of user_wallet.balance
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    public Double getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wallet.balance
     *
     * @param balance the value for user_wallet.balance
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    public void setBalance(Double balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_wallet.user_id
     *
     * @return the value of user_wallet.user_id
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_wallet.user_id
     *
     * @param userId the value for user_wallet.user_id
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}