package org.ecommerceplatform.dao;

import org.apache.ibatis.annotations.Param;
import org.ecommerceplatform.dataobject.ItemStockDO;

public interface ItemStockDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 16 11:08:36 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 16 11:08:36 CST 2022
     */
    int insert(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 16 11:08:36 CST 2022
     */
    int insertSelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 16 11:08:36 CST 2022
     */
    ItemStockDO selectByItemId(Integer id);

    ItemStockDO selectByPrimaryKey(Integer id);

    int decreaseStock(@Param("itemId")Integer itemId, @Param("amount")Integer amount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 16 11:08:36 CST 2022
     */
    int updateByPrimaryKeySelective(ItemStockDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table item_stock
     *
     * @mbg.generated Fri Sep 16 11:08:36 CST 2022
     */
    int updateByPrimaryKey(ItemStockDO record);
}