package org.ecommerceplatform.dao;

import org.ecommerceplatform.dataobject.WalletDO;

import java.math.BigDecimal;

public interface WalletDOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    int insert(WalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    int insertSelective(WalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    WalletDO selectByPrimaryKey(Integer id);

    WalletDO selectByUserId(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    int updateByPrimaryKeySelective(WalletDO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_wallet
     *
     * @mbg.generated Thu Dec 22 22:47:43 GMT 2022
     */
    int updateByPrimaryKey(WalletDO record);

    void decreaseBalance(Integer userId, BigDecimal cost);

    void increaseBalance(Integer userId, BigDecimal cost);
}